version: '3.3'

services:
  db:
    image: mysql:8.0.22
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: db_ausleihe
      MYSQL_USER: ausleihe
      MYSQL_PASSWORD: labor
